const CHANGE_MAIN_FILTER = 'CHANGE_MAIN_FILTER';
const CHANGE_CHECKBOX_FILTER = 'CHANGE_CHECKBOX_FILTER';
const GET_TICKETS_STARTED = 'GET_TICKETS_STARTED';
const GET_TICKETS_COMPLETED = 'GET_TICKETS_COMPLETED';
const FETCH_END = 'FETCH_END';
const ADD_COUNT_OF_SHOWING_TICKETS = 'ADD_COUNT_OF_SHOWING_TICKETS';

export {
  CHANGE_CHECKBOX_FILTER,
  CHANGE_MAIN_FILTER,
  GET_TICKETS_STARTED,
  GET_TICKETS_COMPLETED,
  FETCH_END,
  ADD_COUNT_OF_SHOWING_TICKETS,
};
